services:
  actual-api-rest:
    build: .
    container_name: actual-api-rest
    ports:
      - "5007:8000"
    env_file:
      - .env
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5007/health"]
      interval: 30s
      timeout: 10s
      retries: 3